// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoyaqC2Rwwx3aWr8neLudLT53WOCITdyI',
    appId: '1:770464636292:web:c6e0870d74ef0ca66551d1',
    messagingSenderId: '770464636292',
    projectId: 'app-kebudyaan-lobar',
    authDomain: 'app-kebudyaan-lobar.firebaseapp.com',
    storageBucket: 'app-kebudyaan-lobar.firebasestorage.app',
    measurementId: 'G-SGXY2XB47P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkbr4_jkpelCbTDC-BGbshzM8cx4LbL0U',
    appId: '1:770464636292:android:6bb60676c26c76156551d1',
    messagingSenderId: '770464636292',
    projectId: 'app-kebudyaan-lobar',
    storageBucket: 'app-kebudyaan-lobar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiz5Plsq5E7WlnO0CYiZy8drhgPLYMepc',
    appId: '1:770464636292:ios:d4be2180ebfaecc66551d1',
    messagingSenderId: '770464636292',
    projectId: 'app-kebudyaan-lobar',
    storageBucket: 'app-kebudyaan-lobar.firebasestorage.app',
    iosBundleId: 'com.example.appKebudyaanLobar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiz5Plsq5E7WlnO0CYiZy8drhgPLYMepc',
    appId: '1:770464636292:ios:d4be2180ebfaecc66551d1',
    messagingSenderId: '770464636292',
    projectId: 'app-kebudyaan-lobar',
    storageBucket: 'app-kebudyaan-lobar.firebasestorage.app',
    iosBundleId: 'com.example.appKebudyaanLobar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoyaqC2Rwwx3aWr8neLudLT53WOCITdyI',
    appId: '1:770464636292:web:6330c57499e6deff6551d1',
    messagingSenderId: '770464636292',
    projectId: 'app-kebudyaan-lobar',
    authDomain: 'app-kebudyaan-lobar.firebaseapp.com',
    storageBucket: 'app-kebudyaan-lobar.firebasestorage.app',
    measurementId: 'G-LP40X696D1',
  );
}
