name: Build Android APK

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Optimize Gradle Memory
        run: echo "org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G" >> android/gradle.properties

      - name: Build APK (Bypass Error)
        continue-on-error: true
        run: flutter build apk --release

      - name: Upload APK file
        uses: actions/upload-artifact@v4
        with:
          name: SIBUD-LOBAR-Release-APK
          path: build/app/outputs/**/*.apk